import { useSignIn } from '@/hooks/useSignIn';
import Head from 'next/head'

export default function SignIn() {

  const { email, setEmail, password, setPassword, isSubmitting, handleSubmit } = useSignIn();
  
  return (
    <>
      <Head>
        <title>Sign In</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="flex items-center justify-center min-h-screen bg-gray-100">
          <div className="px-8 py-6 mt-4 text-left bg-white shadow-lg">
            <h3 className="text-2xl font-bold text-center">Sign In</h3>
            <form 
              onSubmit={handleSubmit}
            >
              <div className="mt-4">
                  <div>
                      <label className="block" >Email</label>
                              <input onChange={(e) => setEmail(e.target.value)} type="text" placeholder="Email"
                                  className="w-full px-4 py-2 mt-2 border rounded-md focus:outline-none focus:ring-1 focus:ring-blue-600" />
                  </div>
                  <div className="mt-4">
                      <label className="block">Password</label>
                              <input onChange={(e) => setPassword(e.target.value)} type="password" placeholder="Password"
                                  className="w-full px-4 py-2 mt-2 border rounded-md focus:outline-none focus:ring-1 focus:ring-blue-600" />
                  </div>
                  <div className="flex items-baseline justify-between">
                      <button
                       className="px-6 py-2 mt-4 mr-3 text-white bg-blue-600 rounded-lg hover:bg-blue-900">ログイン</button>
                      <a href="#" className="text-sm text-blue-600 hover:underline">パスワードを忘れましたか?</a>
                  </div>
              </div>
            </form>
          </div>
        </div>
      </main>
    </>
  )
}
